// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthService creates a new instance of MockHealthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthService {
	mock := &MockHealthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthService is an autogenerated mock type for the HealthService type
type MockHealthService struct {
	mock.Mock
}

type MockHealthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthService) EXPECT() *MockHealthService_Expecter {
	return &MockHealthService_Expecter{mock: &_m.Mock}
}

// IsHealthy provides a mock function for the type MockHealthService
func (_mock *MockHealthService) IsHealthy(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for IsHealthy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHealthService_IsHealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsHealthy'
type MockHealthService_IsHealthy_Call struct {
	*mock.Call
}

// IsHealthy is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockHealthService_Expecter) IsHealthy(context1 interface{}) *MockHealthService_IsHealthy_Call {
	return &MockHealthService_IsHealthy_Call{Call: _e.mock.On("IsHealthy", context1)}
}

func (_c *MockHealthService_IsHealthy_Call) Run(run func(context1 context.Context)) *MockHealthService_IsHealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthService_IsHealthy_Call) Return(err error) *MockHealthService_IsHealthy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHealthService_IsHealthy_Call) RunAndReturn(run func(context1 context.Context) error) *MockHealthService_IsHealthy_Call {
	_c.Call.Return(run)
	return _c
}
