// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service_mocks

import (
	"context"
	"goddd/internal/application/dto"
	"goddd/internal/domain/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// CreateNewUser provides a mock function for the type MockUserService
func (_mock *MockUserService) CreateNewUser(context1 context.Context, createUserRequest dto.CreateUserRequest) (models.User, error) {
	ret := _mock.Called(context1, createUserRequest)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewUser")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateUserRequest) (models.User, error)); ok {
		return returnFunc(context1, createUserRequest)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, dto.CreateUserRequest) models.User); ok {
		r0 = returnFunc(context1, createUserRequest)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, dto.CreateUserRequest) error); ok {
		r1 = returnFunc(context1, createUserRequest)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_CreateNewUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewUser'
type MockUserService_CreateNewUser_Call struct {
	*mock.Call
}

// CreateNewUser is a helper method to define mock.On call
//   - context1 context.Context
//   - createUserRequest dto.CreateUserRequest
func (_e *MockUserService_Expecter) CreateNewUser(context1 interface{}, createUserRequest interface{}) *MockUserService_CreateNewUser_Call {
	return &MockUserService_CreateNewUser_Call{Call: _e.mock.On("CreateNewUser", context1, createUserRequest)}
}

func (_c *MockUserService_CreateNewUser_Call) Run(run func(context1 context.Context, createUserRequest dto.CreateUserRequest)) *MockUserService_CreateNewUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 dto.CreateUserRequest
		if args[1] != nil {
			arg1 = args[1].(dto.CreateUserRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_CreateNewUser_Call) Return(user models.User, err error) *MockUserService_CreateNewUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_CreateNewUser_Call) RunAndReturn(run func(context1 context.Context, createUserRequest dto.CreateUserRequest) (models.User, error)) *MockUserService_CreateNewUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockUserService
func (_mock *MockUserService) GetUser(context1 context.Context, uUID uuid.UUID) (*models.User, error) {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.User, error)); ok {
		return returnFunc(context1, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.User); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(context1, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserService_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockUserService_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *MockUserService_Expecter) GetUser(context1 interface{}, uUID interface{}) *MockUserService_GetUser_Call {
	return &MockUserService_GetUser_Call{Call: _e.mock.On("GetUser", context1, uUID)}
}

func (_c *MockUserService_GetUser_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *MockUserService_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_GetUser_Call) Return(user *models.User, err error) *MockUserService_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserService_GetUser_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) (*models.User, error)) *MockUserService_GetUser_Call {
	_c.Call.Return(run)
	return _c
}
