services:
  server:
    build: .
    working_dir: /go-ddd
    volumes:
      - .:/go-ddd:rw
    env_file: .env
    ports:
      - 8000:8000
    tty: true
    stop_signal: SIGINT
    #depends_on:
      #db:
      #  condition: service_healthy
      #db-migration:
      #  condition: service_completed_successfully
    entrypoint: tail -f /dev/null
    # entrypoint: ./db/pgwait.sh
    # command: go run src/main.go
    # healthcheck:
    #     test: curl --fail localhost:8000/health || exit 1
    #     interval: 10s
    #     timeout: 3s
    #     retries: 3
  

  # api:
  #   build: .
  #   command: ["/app/api"]
  #   depends_on:
  #     migrate:
  #       condition: service_completed_successfully

  # migrate:
  #   build: .
  #   command: ["/app/migrate", "-cmd=up"]
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@db:5432/myapp?sslmode=disable
  #   depends_on:
  #     db:
  #       condition: service_healthy

  db:
    image: postgres:18
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PWD
    command: postgres -c log_statement=all
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -h $DB_HOST -U $DB_USER
      interval: 5s
      timeout: 3s
      retries: 2

  db-migration:
    image: liquibase/liquibase:4.33
    depends_on:
      db:
        condition: service_healthy
    profiles: 
      - dev
    volumes:
      - ./db/migrations/liquibase/:/liquibase/changelog/
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://$DB_HOST:$DB_PORT/$DB_NAME
      LIQUIBASE_COMMAND_USERNAME: $DB_USER
      LIQUIBASE_COMMAND_PASSWORD: $DB_PWD
    command: --defaults-file=changelog/liquibase.properties --search-path=changelog update
