services:

  ## Database
  db:
    image: postgres:18
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_PASSWORD=$DB_PWD
    command: postgres -c log_statement=all
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -h $DB_HOST -U $DB_USER
      interval: 5s
      timeout: 3s
      retries: 2

  ## Migration
  migrate:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ["/app/migrate", "-cmd=up"]
    profiles:
      - dev
      - prod
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  # Migration for e2e tests
  migrate-e2e:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ["/app/migrate", "-cmd=up"]
    profiles:
      - e2e
    env_file: .env.test
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /go-ddd
    profiles:
       - dev
    volumes:
      - .:/go-ddd:rw
    env_file: .env
    ports:
      - 8000:8000
    tty: true
    stop_signal: SIGINT
    depends_on:
      migrate:
       condition: service_completed_successfully
    entrypoint: tail -f /dev/null

  app-e2e:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ["/app/api"]
    profiles:
      - e2e
    env_file: .env.test
    ports:
      - 8001:8000
    depends_on:
      migrate-e2e:
        condition: service_completed_successfully
    healthcheck:
        test: curl --fail localhost:8000/health || exit 1
        interval: 10s
        timeout: 3s
        retries: 3

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ["/app/api"]
    profiles:
      - prod
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
        test: curl --fail localhost:8000/health || exit 1
        interval: 10s
        timeout: 3s
        retries: 3
