// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BulkCreateUsers(ctx context.Context, arg *BulkCreateUsersParams) ([]*User, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetUserByID(ctx context.Context, id pgtype.UUID) (*User, error)
	ListUsersPaged(ctx context.Context, arg *ListUsersPagedParams) ([]*User, error)
	UpdateUser(ctx context.Context, arg *UpdateUserParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
