// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkCreateUsers = `-- name: BulkCreateUsers :many
INSERT INTO users (email, username)
SELECT unnest($1::text[]), unnest($2::text[])
RETURNING id, email, username, created_at, updated_at
`

type BulkCreateUsersParams struct {
	Emails    []string
	Usernames []string
}

func (q *Queries) BulkCreateUsers(ctx context.Context, arg *BulkCreateUsersParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, bulkCreateUsers, arg.Emails, arg.Usernames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username) 
VALUES ($1, $2)
RETURNING id, email, username, created_at, updated_at
`

type CreateUserParams struct {
	Email    string
	Username string
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listUsersPaged = `-- name: ListUsersPaged :many
SELECT id, email, username, created_at, updated_at
FROM users
WHERE (
    $1::uuid = '00000000-0000-0000-0000-000000000000'::uuid
    OR created_at < (SELECT created_at FROM users WHERE id = $1::uuid)
    OR (created_at = (SELECT created_at FROM users WHERE id = $1::uuid) AND id > $1::uuid)
)
ORDER BY created_at DESC, id ASC
LIMIT $2
`

type ListUsersPagedParams struct {
	Column1 pgtype.UUID
	Limit   int32
}

func (q *Queries) ListUsersPaged(ctx context.Context, arg *ListUsersPagedParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsersPaged, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    email         = $1,
    username      = $2,
    updated_at    = now()
WHERE id = $3
RETURNING id, email, username, created_at, updated_at
`

type UpdateUserParams struct {
	Email    string
	Username string
	ID       pgtype.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg *UpdateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.Email, arg.Username, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
