// Code generated by mockery v2.51.1. DO NOT EDIT.

package mockrepo

import (
	models "goddd/src/domain/models"

	mock "github.com/stretchr/testify/mock"
)

// MockCustomerRepository is an autogenerated mock type for the CustomerRepository type
type MockCustomerRepository struct {
	mock.Mock
}

type MockCustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerRepository) EXPECT() *MockCustomerRepository_Expecter {
	return &MockCustomerRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: _a0
func (_m *MockCustomerRepository) Add(_a0 models.Customer) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.Customer) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCustomerRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockCustomerRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - _a0 models.Customer
func (_e *MockCustomerRepository_Expecter) Add(_a0 interface{}) *MockCustomerRepository_Add_Call {
	return &MockCustomerRepository_Add_Call{Call: _e.mock.On("Add", _a0)}
}

func (_c *MockCustomerRepository_Add_Call) Run(run func(_a0 models.Customer)) *MockCustomerRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.Customer))
	})
	return _c
}

func (_c *MockCustomerRepository_Add_Call) Return(_a0 error) *MockCustomerRepository_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCustomerRepository_Add_Call) RunAndReturn(run func(models.Customer) error) *MockCustomerRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: _a0
func (_m *MockCustomerRepository) Delete(_a0 string) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCustomerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCustomerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - _a0 string
func (_e *MockCustomerRepository_Expecter) Delete(_a0 interface{}) *MockCustomerRepository_Delete_Call {
	return &MockCustomerRepository_Delete_Call{Call: _e.mock.On("Delete", _a0)}
}

func (_c *MockCustomerRepository_Delete_Call) Run(run func(_a0 string)) *MockCustomerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCustomerRepository_Delete_Call) Return(_a0 error) *MockCustomerRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCustomerRepository_Delete_Call) RunAndReturn(run func(string) error) *MockCustomerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: _a0
func (_m *MockCustomerRepository) Get(_a0 string) (models.Customer, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.Customer, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) models.Customer); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(models.Customer)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCustomerRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCustomerRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 string
func (_e *MockCustomerRepository_Expecter) Get(_a0 interface{}) *MockCustomerRepository_Get_Call {
	return &MockCustomerRepository_Get_Call{Call: _e.mock.On("Get", _a0)}
}

func (_c *MockCustomerRepository_Get_Call) Run(run func(_a0 string)) *MockCustomerRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCustomerRepository_Get_Call) Return(_a0 models.Customer, _a1 error) *MockCustomerRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCustomerRepository_Get_Call) RunAndReturn(run func(string) (models.Customer, error)) *MockCustomerRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function with given fields: userid
func (_m *MockCustomerRepository) ListByUser(userid string) ([]models.Customer, error) {
	ret := _m.Called(userid)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []models.Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]models.Customer, error)); ok {
		return rf(userid)
	}
	if rf, ok := ret.Get(0).(func(string) []models.Customer); ok {
		r0 = rf(userid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCustomerRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockCustomerRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - userid string
func (_e *MockCustomerRepository_Expecter) ListByUser(userid interface{}) *MockCustomerRepository_ListByUser_Call {
	return &MockCustomerRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", userid)}
}

func (_c *MockCustomerRepository_ListByUser_Call) Run(run func(userid string)) *MockCustomerRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCustomerRepository_ListByUser_Call) Return(_a0 []models.Customer, _a1 error) *MockCustomerRepository_ListByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCustomerRepository_ListByUser_Call) RunAndReturn(run func(string) ([]models.Customer, error)) *MockCustomerRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCustomerRepository creates a new instance of MockCustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerRepository {
	mock := &MockCustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
