// Code generated by mockery v2.51.1. DO NOT EDIT.

package mockrepo

import mock "github.com/stretchr/testify/mock"

// MockHealthRepository is an autogenerated mock type for the HealthRepository type
type MockHealthRepository struct {
	mock.Mock
}

type MockHealthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthRepository) EXPECT() *MockHealthRepository_Expecter {
	return &MockHealthRepository_Expecter{mock: &_m.Mock}
}

// HealthValue provides a mock function with no fields
func (_m *MockHealthRepository) HealthValue() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthValue")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockHealthRepository_HealthValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthValue'
type MockHealthRepository_HealthValue_Call struct {
	*mock.Call
}

// HealthValue is a helper method to define mock.On call
func (_e *MockHealthRepository_Expecter) HealthValue() *MockHealthRepository_HealthValue_Call {
	return &MockHealthRepository_HealthValue_Call{Call: _e.mock.On("HealthValue")}
}

func (_c *MockHealthRepository_HealthValue_Call) Run(run func()) *MockHealthRepository_HealthValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthRepository_HealthValue_Call) Return(_a0 string, _a1 error) *MockHealthRepository_HealthValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockHealthRepository_HealthValue_Call) RunAndReturn(run func() (string, error)) *MockHealthRepository_HealthValue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthRepository creates a new instance of MockHealthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthRepository {
	mock := &MockHealthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
