// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthRepository creates a new instance of MockHealthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthRepository {
	mock := &MockHealthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthRepository is an autogenerated mock type for the HealthRepository type
type MockHealthRepository struct {
	mock.Mock
}

type MockHealthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthRepository) EXPECT() *MockHealthRepository_Expecter {
	return &MockHealthRepository_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type MockHealthRepository
func (_mock *MockHealthRepository) Ping(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHealthRepository_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockHealthRepository_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockHealthRepository_Expecter) Ping(context1 interface{}) *MockHealthRepository_Ping_Call {
	return &MockHealthRepository_Ping_Call{Call: _e.mock.On("Ping", context1)}
}

func (_c *MockHealthRepository_Ping_Call) Run(run func(context1 context.Context)) *MockHealthRepository_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHealthRepository_Ping_Call) Return(err error) *MockHealthRepository_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHealthRepository_Ping_Call) RunAndReturn(run func(context1 context.Context) error) *MockHealthRepository_Ping_Call {
	_c.Call.Return(run)
	return _c
}
