// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository_mocks

import (
	"context"
	"goddd/internal/domain/models"
	"goddd/internal/domain/repository"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// BulkCreates provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) BulkCreates(context1 context.Context, newUsers []models.NewUser) (int64, error) {
	ret := _mock.Called(context1, newUsers)

	if len(ret) == 0 {
		panic("no return value specified for BulkCreates")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.NewUser) (int64, error)); ok {
		return returnFunc(context1, newUsers)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []models.NewUser) int64); ok {
		r0 = returnFunc(context1, newUsers)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []models.NewUser) error); ok {
		r1 = returnFunc(context1, newUsers)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_BulkCreates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkCreates'
type MockUserRepository_BulkCreates_Call struct {
	*mock.Call
}

// BulkCreates is a helper method to define mock.On call
//   - context1 context.Context
//   - newUsers []models.NewUser
func (_e *MockUserRepository_Expecter) BulkCreates(context1 interface{}, newUsers interface{}) *MockUserRepository_BulkCreates_Call {
	return &MockUserRepository_BulkCreates_Call{Call: _e.mock.On("BulkCreates", context1, newUsers)}
}

func (_c *MockUserRepository_BulkCreates_Call) Run(run func(context1 context.Context, newUsers []models.NewUser)) *MockUserRepository_BulkCreates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []models.NewUser
		if args[1] != nil {
			arg1 = args[1].([]models.NewUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_BulkCreates_Call) Return(n int64, err error) *MockUserRepository_BulkCreates_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockUserRepository_BulkCreates_Call) RunAndReturn(run func(context1 context.Context, newUsers []models.NewUser) (int64, error)) *MockUserRepository_BulkCreates_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Create(context1 context.Context, newUser models.NewUser) (models.User, error) {
	ret := _mock.Called(context1, newUser)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.NewUser) (models.User, error)); ok {
		return returnFunc(context1, newUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.NewUser) models.User); ok {
		r0 = returnFunc(context1, newUser)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.NewUser) error); ok {
		r1 = returnFunc(context1, newUser)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - context1 context.Context
//   - newUser models.NewUser
func (_e *MockUserRepository_Expecter) Create(context1 interface{}, newUser interface{}) *MockUserRepository_Create_Call {
	return &MockUserRepository_Create_Call{Call: _e.mock.On("Create", context1, newUser)}
}

func (_c *MockUserRepository_Create_Call) Run(run func(context1 context.Context, newUser models.NewUser)) *MockUserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.NewUser
		if args[1] != nil {
			arg1 = args[1].(models.NewUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Create_Call) Return(user models.User, err error) *MockUserRepository_Create_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_Create_Call) RunAndReturn(run func(context1 context.Context, newUser models.NewUser) (models.User, error)) *MockUserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Delete(context1 context.Context, uUID uuid.UUID) error {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *MockUserRepository_Expecter) Delete(context1 interface{}, uUID interface{}) *MockUserRepository_Delete_Call {
	return &MockUserRepository_Delete_Call{Call: _e.mock.On("Delete", context1, uUID)}
}

func (_c *MockUserRepository_Delete_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *MockUserRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Delete_Call) Return(err error) *MockUserRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Delete_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) error) *MockUserRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindByID(context1 context.Context, uUID uuid.UUID) (*models.User, error) {
	ret := _mock.Called(context1, uUID)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.User, error)); ok {
		return returnFunc(context1, uUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.User); ok {
		r0 = returnFunc(context1, uUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(context1, uUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - context1 context.Context
//   - uUID uuid.UUID
func (_e *MockUserRepository_Expecter) FindByID(context1 interface{}, uUID interface{}) *MockUserRepository_FindByID_Call {
	return &MockUserRepository_FindByID_Call{Call: _e.mock.On("FindByID", context1, uUID)}
}

func (_c *MockUserRepository_FindByID_Call) Run(run func(context1 context.Context, uUID uuid.UUID)) *MockUserRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindByID_Call) Return(user *models.User, err error) *MockUserRepository_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_FindByID_Call) RunAndReturn(run func(context1 context.Context, uUID uuid.UUID) (*models.User, error)) *MockUserRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindPaged provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) FindPaged(context1 context.Context, page repository.Page) (repository.PagedResult, error) {
	ret := _mock.Called(context1, page)

	if len(ret) == 0 {
		panic("no return value specified for FindPaged")
	}

	var r0 repository.PagedResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Page) (repository.PagedResult, error)); ok {
		return returnFunc(context1, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, repository.Page) repository.PagedResult); ok {
		r0 = returnFunc(context1, page)
	} else {
		r0 = ret.Get(0).(repository.PagedResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, repository.Page) error); ok {
		r1 = returnFunc(context1, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_FindPaged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindPaged'
type MockUserRepository_FindPaged_Call struct {
	*mock.Call
}

// FindPaged is a helper method to define mock.On call
//   - context1 context.Context
//   - page repository.Page
func (_e *MockUserRepository_Expecter) FindPaged(context1 interface{}, page interface{}) *MockUserRepository_FindPaged_Call {
	return &MockUserRepository_FindPaged_Call{Call: _e.mock.On("FindPaged", context1, page)}
}

func (_c *MockUserRepository_FindPaged_Call) Run(run func(context1 context.Context, page repository.Page)) *MockUserRepository_FindPaged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 repository.Page
		if args[1] != nil {
			arg1 = args[1].(repository.Page)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_FindPaged_Call) Return(pagedResult repository.PagedResult, err error) *MockUserRepository_FindPaged_Call {
	_c.Call.Return(pagedResult, err)
	return _c
}

func (_c *MockUserRepository_FindPaged_Call) RunAndReturn(run func(context1 context.Context, page repository.Page) (repository.PagedResult, error)) *MockUserRepository_FindPaged_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Update(context1 context.Context, user models.User) (models.User, error) {
	ret := _mock.Called(context1, user)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.User) (models.User, error)); ok {
		return returnFunc(context1, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.User) models.User); ok {
		r0 = returnFunc(context1, user)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, models.User) error); ok {
		r1 = returnFunc(context1, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockUserRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - context1 context.Context
//   - user models.User
func (_e *MockUserRepository_Expecter) Update(context1 interface{}, user interface{}) *MockUserRepository_Update_Call {
	return &MockUserRepository_Update_Call{Call: _e.mock.On("Update", context1, user)}
}

func (_c *MockUserRepository_Update_Call) Run(run func(context1 context.Context, user models.User)) *MockUserRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.User
		if args[1] != nil {
			arg1 = args[1].(models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_Update_Call) Return(user1 models.User, err error) *MockUserRepository_Update_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepository_Update_Call) RunAndReturn(run func(context1 context.Context, user models.User) (models.User, error)) *MockUserRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
