// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"goddd/domain/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHealthRepository creates a new instance of MockHealthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthRepository {
	mock := &MockHealthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHealthRepository is an autogenerated mock type for the HealthRepository type
type MockHealthRepository struct {
	mock.Mock
}

type MockHealthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthRepository) EXPECT() *MockHealthRepository_Expecter {
	return &MockHealthRepository_Expecter{mock: &_m.Mock}
}

// HealthValue provides a mock function for the type MockHealthRepository
func (_mock *MockHealthRepository) HealthValue() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthValue")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHealthRepository_HealthValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthValue'
type MockHealthRepository_HealthValue_Call struct {
	*mock.Call
}

// HealthValue is a helper method to define mock.On call
func (_e *MockHealthRepository_Expecter) HealthValue() *MockHealthRepository_HealthValue_Call {
	return &MockHealthRepository_HealthValue_Call{Call: _e.mock.On("HealthValue")}
}

func (_c *MockHealthRepository_HealthValue_Call) Run(run func()) *MockHealthRepository_HealthValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHealthRepository_HealthValue_Call) Return(s string, err error) *MockHealthRepository_HealthValue_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockHealthRepository_HealthValue_Call) RunAndReturn(run func() (string, error)) *MockHealthRepository_HealthValue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// GetById provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetById(id string) (models.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (models.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockUserRepository_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - id string
func (_e *MockUserRepository_Expecter) GetById(id interface{}) *MockUserRepository_GetById_Call {
	return &MockUserRepository_GetById_Call{Call: _e.mock.On("GetById", id)}
}

func (_c *MockUserRepository_GetById_Call) Run(run func(id string)) *MockUserRepository_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetById_Call) Return(user models.User, err error) *MockUserRepository_GetById_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetById_Call) RunAndReturn(run func(id string) (models.User, error)) *MockUserRepository_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByUsername(username string) (models.User, error) {
	ret := _mock.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (models.User, error)); ok {
		return returnFunc(username)
	}
	if returnFunc, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = returnFunc(username)
	} else {
		r0 = ret.Get(0).(models.User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockUserRepository_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - username string
func (_e *MockUserRepository_Expecter) GetByUsername(username interface{}) *MockUserRepository_GetByUsername_Call {
	return &MockUserRepository_GetByUsername_Call{Call: _e.mock.On("GetByUsername", username)}
}

func (_c *MockUserRepository_GetByUsername_Call) Run(run func(username string)) *MockUserRepository_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByUsername_Call) Return(user models.User, err error) *MockUserRepository_GetByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetByUsername_Call) RunAndReturn(run func(username string) (models.User, error)) *MockUserRepository_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCustomerRepository creates a new instance of MockCustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerRepository {
	mock := &MockCustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomerRepository is an autogenerated mock type for the CustomerRepository type
type MockCustomerRepository struct {
	mock.Mock
}

type MockCustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerRepository) EXPECT() *MockCustomerRepository_Expecter {
	return &MockCustomerRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) Add(customer models.Customer) error {
	ret := _mock.Called(customer)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.Customer) error); ok {
		r0 = returnFunc(customer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockCustomerRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - customer models.Customer
func (_e *MockCustomerRepository_Expecter) Add(customer interface{}) *MockCustomerRepository_Add_Call {
	return &MockCustomerRepository_Add_Call{Call: _e.mock.On("Add", customer)}
}

func (_c *MockCustomerRepository_Add_Call) Run(run func(customer models.Customer)) *MockCustomerRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.Customer
		if args[0] != nil {
			arg0 = args[0].(models.Customer)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_Add_Call) Return(err error) *MockCustomerRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerRepository_Add_Call) RunAndReturn(run func(customer models.Customer) error) *MockCustomerRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) Delete(s string) error {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCustomerRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - s string
func (_e *MockCustomerRepository_Expecter) Delete(s interface{}) *MockCustomerRepository_Delete_Call {
	return &MockCustomerRepository_Delete_Call{Call: _e.mock.On("Delete", s)}
}

func (_c *MockCustomerRepository_Delete_Call) Run(run func(s string)) *MockCustomerRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_Delete_Call) Return(err error) *MockCustomerRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerRepository_Delete_Call) RunAndReturn(run func(s string) error) *MockCustomerRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) Get(s string) (models.Customer, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 models.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (models.Customer, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) models.Customer); ok {
		r0 = returnFunc(s)
	} else {
		r0 = ret.Get(0).(models.Customer)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCustomerRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - s string
func (_e *MockCustomerRepository_Expecter) Get(s interface{}) *MockCustomerRepository_Get_Call {
	return &MockCustomerRepository_Get_Call{Call: _e.mock.On("Get", s)}
}

func (_c *MockCustomerRepository_Get_Call) Run(run func(s string)) *MockCustomerRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_Get_Call) Return(customer models.Customer, err error) *MockCustomerRepository_Get_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockCustomerRepository_Get_Call) RunAndReturn(run func(s string) (models.Customer, error)) *MockCustomerRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) ListByUser(userid string) ([]models.Customer, error) {
	ret := _mock.Called(userid)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []models.Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]models.Customer, error)); ok {
		return returnFunc(userid)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []models.Customer); ok {
		r0 = returnFunc(userid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockCustomerRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - userid string
func (_e *MockCustomerRepository_Expecter) ListByUser(userid interface{}) *MockCustomerRepository_ListByUser_Call {
	return &MockCustomerRepository_ListByUser_Call{Call: _e.mock.On("ListByUser", userid)}
}

func (_c *MockCustomerRepository_ListByUser_Call) Run(run func(userid string)) *MockCustomerRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_ListByUser_Call) Return(customers []models.Customer, err error) *MockCustomerRepository_ListByUser_Call {
	_c.Call.Return(customers, err)
	return _c
}

func (_c *MockCustomerRepository_ListByUser_Call) RunAndReturn(run func(userid string) ([]models.Customer, error)) *MockCustomerRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}
