# Top-level defaults config
template: testify
# default directory
dir: 'tests/mocks'
all: false
# packages to generate the mock files
pkgname: '{{.SrcPackageName}}'
packages:
  goddd/internal/domain/repository:
    config:
      dir: tests/mocks/repository
      filename: '{{.InterfaceName | snakecase | lower }}.go'
      pkgname: repository_mocks
      all: true
  goddd/internal/application/transaction:
    config:
      dir: tests/mocks/transaction
      filename: 'transaction.go'
      pkgname: transaction_mocks
      all: true